tap 'homebrew/services'

brew 'git'
brew 'ack'
brew 'ctags'
brew 'exif'
brew 'heroku-toolbelt'
brew 'imagemagick'
brew 'libyaml'
brew 'node'
brew 'openssl'
brew 'postgres', restart_service: true
brew 'postgis'
brew 'redis', restart_service: true
brew 'the_silver_searcher'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'selecta'
brew 'yajl'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'cloak'
cask 'font-input'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2-nightly'
cask 'mailplane'
cask 'screenhero'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'tunnelblick'
cask 'vlc'
