#!/bin/sh

echo "Linking dotfiles..."
ln -s ~/dev/dotfiles/git ~/.gitconfig
ln -s ~/dev/dotfiles/gitignore ~/.gitignore_global
ln -s ~/dev/dotfiles/vim ~/.vimrc
ln -s ~/dev/dotfiles/zsh ~/.zshrc
ln -s ~/dev/dotfiles/gem ~/.gemrc
ln -s ~/dev/dotfiles/pry ~/.pryrc
ln -s ~/dev/dotfiles/rvm ~/.rvmrc
ln -s ~/dev/dotfiles/ag ~/.agignore
ln -s ~/dev/dotfiles/spring ~/.spring.rb

echo "Installing vim plug..."
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Downloading vim color themes..."
mkdir ~/.vim/colors
(cd ~/.vim/colors && wget https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/vim/colors/Tomorrow-Night.vim)
(cd ~/.vim/colors && wget https://raw.githubusercontent.com/chriskempson/tomorrow-theme/master/vim/colors/Tomorrow.vim)

echo "Done"
