#!/bin/sh

set -e

if [ ! $(which brew) ]; then
  echo "[dotfiles] Installing homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "[dotfiles] Installing dependencies via Homebrew..."
brew bundle

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "[dotfiles] Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

echo "[dotfiles] Linking dotfiles..."
ln -s $(pwd)/gitconfig $HOME/.gitconfig
ln -s $(pwd)/gitignore $HOME/.gitignore_global
ln -s $(pwd)/vimrc $HOME/.vimrc
ln -s $(pwd)/zshrc $HOME/.zshrc
ln -s $(pwd)/gem $HOME/.gemrc
ln -s $(pwd)/pry $HOME/.pryrc
ln -s $(pwd)/rvm $HOME/.rvmrc
ln -s $(pwd)/ag $HOME/.agignore
ln -s $(pwd)/spring $HOME/.spring.rb
ln -s $(pwd)/speric.zsh-theme $HOME/.oh-my-zsh/themes/speric.zsh-theme

echo "[dotfiles] Installing vim-plug..."
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "[dotfiles] Installing vim plugins..."
vim +PlugInstall +qall

echo "[dotfiles] Downloading iTerm color themes..."
mkdir $HOME/.iterm
(cd $HOME/.iterm && curl -O https://raw.githubusercontent.com/trevordmiller/nova-iterm/master/build/nova.itermcolors)

echo "[dotfiles] Configuring fzf command line helpers..."
$(brew --prefix)/opt/fzf/install

echo "[dotfiles] Done!"
